import type {Metadata} from 'next';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight,Mountain,Footprints,Landmark} from 'lucide-react';
import {Header,Footer} from '@/components/site-ui';
import {mountains,type MountainDifficulty} from '@/data/mountains';

export const metadata:Metadata={title:'서울 산 BEST 10 | 서울픽',description:'지하철로 떠나는 서울의 산과 전망 산책길. 난이도·시간·풍경을 비교하고 산별 가이드를 확인하세요.',alternates:{canonical:'/mountains'},openGraph:{title:'서울 산 BEST 10',description:'성곽길 산책부터 바위 정상에 오르는 하루까지',images:['/mountains/inwangsan/01.jpg']}};
type Props={searchParams:Promise<{difficulty?:string;time?:string;tag?:string}>};
export default async function MountainHub({searchParams}:Props){const q=await searchParams;const difficulty=q.difficulty as MountainDifficulty|undefined;const filtered=mountains.filter(m=>(!difficulty||m.difficulty===difficulty)&&(!q.time||(q.time==='short'?['낙산','남산','응봉산'].includes(m.name):q.time==='half'?['인왕산','북악산','아차산','서대문 안산'].includes(m.name):['북한산','도봉산','관악산'].includes(m.name)))&&(!q.tag||m.tags.includes(q.tag)));
 return <><Header/><main className="inner-main"><section className="mountain-hub-hero"><Image src="/mountains/inwangsan/01.jpg" alt="인왕산에서 바라본 서울 도심과 산세" width={1600} height={900} sizes="100vw" loading="eager"/><div><span>서울픽 추천 10선</span><h1>서울 산 BEST 10</h1><p>성곽길 산책부터 바위 정상에 오르는 하루까지.<br/>내 일정과 체력에 맞는 서울의 산을 찾아보세요.</p><small>교통편, 전망, 대표 코스 난이도와 여행 동선을 고려해 고른 10곳입니다. 번호는 소개 순서입니다.</small></div></section><div className="wrap mountain-page"><nav className="breadcrumbs" aria-label="현재 위치"><Link href="/">홈</Link><span>/ 서울의 산</span></nav><nav className="mountain-jump-nav" aria-label="서울의 산 페이지 바로가기"><a href="#best10">BEST 10 전체 보기</a><a href="#find-your-hike">내게 맞는 산 찾기</a><a href="#before-you-go">산행 준비</a></nav>
 <section className="mountain-types" aria-labelledby="type-title"><h2 id="type-title">어떤 산행을 원하세요?</h2><div><article><Footprints/><h3>가벼운 산책</h3><p>응봉산·낙산·서대문 안산</p></article><article><Landmark/><h3>성곽과 역사</h3><p>인왕산·북악산·낙산</p></article><article><Mountain/><h3>정상 도전</h3><p>북한산·도봉산·관악산</p></article></div></section>
 <form id="find-your-hike" className="mountain-filters"><label>난이도<select name="difficulty" defaultValue={q.difficulty||''}><option value="">전체</option><option>쉬움</option><option>보통</option><option>어려움</option></select></label><label>예상 일정<select name="time" defaultValue={q.time||''}><option value="">전체</option><option value="short">짧은 산책</option><option value="half">반나절</option><option value="day">하루 산행</option></select></label><label>풍경<select name="tag" defaultValue={q.tag||''}><option value="">전체</option><option value="전망">전망</option><option value="성곽">성곽</option><option value="숲길">숲길</option><option value="한강">한강</option><option value="정상">정상</option></select></label><button className="button" type="submit">조건 적용</button><Link href="/mountains" className="reset-link">초기화</Link></form>
 <p id="best10" className="result-count">조건에 맞는 산 {filtered.length}곳</p>{filtered.length?<section className="mountain-grid">{filtered.map(m=><article className="mountain-card" key={m.slug}><Link href={'/mountains/'+m.slug}><Image src={m.images[0].src} alt={m.images[0].alt} width={700} height={520} sizes="(max-width: 700px) 100vw, 230px"/></Link><div><span>{String(m.number).padStart(2,'0')} · {m.difficulty} · {m.routeType}</span><h2><Link href={'/mountains/'+m.slug}>{m.displayName||m.name}</Link></h2><p>{m.summary}</p><dl><div><dt>출발</dt><dd>{m.station} ({m.stationEn}) {m.exit}</dd></div><div><dt>시간</dt><dd>{m.duration}</dd></div></dl><Link href={'/mountains/'+m.slug} className="text-link">가이드 보기 <ArrowRight size={16}/></Link></div></article>)}</section>:<div className="empty"><Mountain size={34}/><h2>조건에 맞는 산이 없습니다</h2><p>난이도, 일정 또는 풍경 조건을 바꿔 보세요.</p><Link href="/mountains" className="button">전체 10곳 보기</Link></div>}
 <section className="mountain-compare"><h2>한눈에 비교</h2><div className="blog-table-scroll"><table><thead><tr><th>산</th><th>출발점</th><th>도착점</th><th>거리</th><th>예상 시간</th><th>형태</th><th>난이도</th></tr></thead><tbody>{mountains.map(m=><tr key={m.slug}><td><Link href={'/mountains/'+m.slug}>{m.displayName||m.name}</Link></td><td>{m.trailhead}</td><td>{m.end}</td><td>{m.distance}</td><td>{m.duration}</td><td>{m.routeType}</td><td>{m.difficulty}</td></tr>)}</tbody></table></div><p className="source-note">시간은 각 행의 대표 코스 범위입니다. 지하철역 접근, 긴 휴식과 사진 촬영은 별도로 더하세요.</p></section>
 <section id="before-you-go" className="mountain-help"><h2>첫 산행 전에</h2><div><article><h3>신발과 물</h3><p>높이보다 노면과 날씨가 난이도를 크게 바꿉니다. 바위·계단 코스는 접지력 있는 신발을 신고 물을 준비하세요.</p></article><article><h3>지도와 통제</h3><p>입구 길찾기와 등산 코스 지도를 구분하고, 출발 전 공식 통제와 기상특보를 확인하세요.</p></article><article><h3>장비 대여</h3><p>북한산우이역과 관악산역의 서울도심등산관광센터는 운영시간과 대여 품목을 확인한 뒤 이용하세요.</p><a href="https://seoulhiking.or.kr/" target="_blank" rel="noopener noreferrer" className="text-link">공식 안내 열기 <ArrowRight size={16}/></a></article></div></section>
 <section className="related-blog"><div className="section-head"><h2>산행 전 함께 볼 가이드</h2><Link href="/guides" className="text-link">여행 가이드 전체 보기 <ArrowRight size={16}/></Link></div><div className="blog-related-links"><Link href="/guides/transit">서울 대중교통 이용법 <ArrowRight size={16}/></Link><Link href="/guides/packing">서울 여행 준비 체크리스트 <ArrowRight size={16}/></Link><Link href="/itineraries/seoul-night">남산과 도심 야경 코스 <ArrowRight size={16}/></Link></div></section></div></main><Footer/></>}
