'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useState,useSyncExternalStore} from 'react';
import {Heart,Menu,X,MapPin,Globe2,ArrowRight,Search,Bookmark,ExternalLink,Copy} from 'lucide-react';
import {places} from '@/data/content';
function PinLogo({size=30}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 64 64" aria-hidden="true"><path fill="#ff644f" d="M32 2C19 2 9 12 9 25c0 16 23 37 23 37s23-21 23-37C55 12 45 2 32 2Z"/><circle cx="32" cy="25" r="9" fill="white"/></svg>}
const nav=[['지역별 탐색','/areas'],['서울의 산','/mountains'],['명소·체험','/attractions'],['맛집·카페','/food'],['추천 코스','/itineraries'],['K-컬처','/k-culture'],['여행 가이드','/guides'],['블로그','/blog']];
export function Header(){const [open,setOpen]=useState(false);const pathname=usePathname();const current=(url:string)=>pathname===url||pathname.startsWith(url+'/');return <header className="site-header"><div className="header-inner"><Link href="/" className="brand" onClick={()=>setOpen(false)}><PinLogo/><span><strong>서울픽</strong><small>SEOUL PICK</small></span></Link><nav className="desktop-nav" aria-label="주 메뉴">{nav.map(([label,url])=><Link className={current(url)?'current':''} aria-current={current(url)?'page':undefined} key={url} href={url}>{label}</Link>)}</nav><div className="header-actions"><Link href="/search" aria-label="검색"><Search size={18}/></Link><Link href="/saved" aria-label="저장한 장소" className="saved-link"><Heart size={18}/> <span>저장</span></Link><span className="language"><Globe2 size={17}/> 한국어</span><button type="button" className="menu-toggle" aria-label={open?'메뉴 닫기':'메뉴 열기'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav className="mobile-nav" aria-label="모바일 메뉴">{nav.map(([label,url])=><Link className={current(url)?'current':''} aria-current={current(url)?'page':undefined} onClick={()=>setOpen(false)} key={url} href={url}>{label}<ArrowRight size={17}/></Link>)}<Link onClick={()=>setOpen(false)} href="/search">검색<Search size={17}/></Link><Link onClick={()=>setOpen(false)} href="/saved">저장한 장소<Heart size={17}/></Link></nav>}</header>}
export function Footer(){return <footer className="footer"><div className="wrap footer-inner"><Link href="/" className="brand"><PinLogo size={26}/><span><strong>서울픽</strong><small>SEOUL PICK</small></span></Link><nav aria-label="푸터 메뉴"><Link href="/mountains">서울의 산</Link><Link href="/blog">블로그</Link><Link href="/about">소개</Link><Link href="/partnership">제휴 안내</Link><Link href="/privacy">개인정보처리방침</Link><Link href="/terms">이용약관</Link><Link href="/photo-credits">사진 출처</Link></nav></div></footer>}
const storageKey='seoul-pick-saved';
export function getSaved():string[]{try{return JSON.parse(localStorage.getItem(storageKey)||'[]')}catch{return []}}
const subscribeSaved=(callback:()=>void)=>{window.addEventListener('seoul-saved',callback);window.addEventListener('storage',callback);return()=>{window.removeEventListener('seoul-saved',callback);window.removeEventListener('storage',callback)}};
const savedSnapshot=()=>localStorage.getItem(storageKey)||'[]';
export function SaveButton({id,compact=false}:{id:string;compact?:boolean}){const snapshot=useSyncExternalStore(subscribeSaved,savedSnapshot,()=> '[]');const saved=(JSON.parse(snapshot) as string[]).includes(id);return <button type="button" className={'save-button '+(saved?'is-saved':'')+(compact?' compact':'')} aria-label={`${places.find(p=>p.id===id)?.name||'장소'} ${saved?'저장 해제':'저장하기'}`} aria-pressed={saved} onClick={()=>{const current=getSaved();const next=saved?current.filter(x=>x!==id):[...current,id];localStorage.setItem(storageKey,JSON.stringify(next));window.dispatchEvent(new Event('seoul-saved'))}}><Bookmark size={compact?19:18} fill={saved?'currentColor':'none'}/>{!compact&&<span>{saved?'저장됨':'저장하기'}</span>}</button>}
export function SaveAllButton({ids}:{ids:string[]}){const [done,setDone]=useState(false);return <button className="button button-outline" onClick={()=>{localStorage.setItem(storageKey,JSON.stringify([...new Set([...getSaved(),...ids])]));window.dispatchEvent(new Event('seoul-saved'));setDone(true)}}><Bookmark size={17}/>{done?'코스 장소 저장됨':'코스 장소 모두 저장'}</button>}
export function SavedList(){const snapshot=useSyncExternalStore(subscribeSaved,savedSnapshot,()=> '[]');const ids=JSON.parse(snapshot) as string[];const items=places.filter(p=>ids.includes(p.id));return items.length?<div className="place-grid">{items.map(p=><PlaceCard key={p.id} place={p}/>)}</div>:<div className="empty"><Heart size={34}/><h2>아직 저장한 장소가 없어요</h2><p>여행 중 가고 싶은 곳을 저장해 보세요.</p><Link href="/attractions" className="button">장소 둘러보기 <ArrowRight size={17}/></Link></div>}
export function PlaceCard({place:p}:{place:typeof places[number]}){return <article className="place-card"><Link href={'/places/'+p.id} className="card-image-link"><Photo src={p.image} alt={p.name} className="card-image" label={p.kind}/></Link><div className="place-card-body"><span className="eyebrow-dark">{p.kind}</span><Link href={'/places/'+p.id}><h3>{p.name}</h3></Link><p>{p.summary}</p><div className="card-bottom"><Link href={'/places/'+p.id} className="text-link">자세히 보기 <ArrowRight size={16}/></Link><SaveButton id={p.id} compact/></div></div></article>}
export function Photo({src,alt,className='',label}:{src?:string;alt:string;className?:string;label?:string}){return src?<img className={className} src={src} alt={alt} loading="lazy"/>:<div className={`${className} photo-fallback`} role="img" aria-label={`${alt} 사진 준비 중`}><MapPin size={30}/><span>{label||alt}</span><small>사진 준비 중</small></div>}
export function SearchForm({initial=''}:{initial?:string}){return <form action="/search" className="search-form"><Search size={23} aria-hidden="true"/><input type="search" name="q" defaultValue={initial} placeholder="가고 싶은 동네, 음식, 장소를 검색해 보세요" aria-label="장소 검색"/><button type="submit">검색</button></form>}
export function AddressCopy({address}:{address:string}){const [copied,setCopied]=useState(false);return <button type="button" className="inline-button" onClick={async()=>{try{await navigator.clipboard.writeText(address);setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{setCopied(false)}}}><Copy size={16}/>{copied?'복사됨':'주소 복사'}</button>}
export function External({href,children}:{href:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noopener noreferrer">{children}<ExternalLink size={15} aria-hidden="true"/></a>}


