import type {Metadata} from 'next';
import Link from 'next/link';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {ArrowRight,ExternalLink,MapPin,TrainFront} from 'lucide-react';
import {Header,Footer,AddressCopy} from '@/components/site-ui';
import {MountainSave} from '@/components/mountain-save';
import {mountains,mountainBySlug} from '@/data/mountains';
import {siteOrigin} from '@/lib/site-url';
type Props={params:Promise<{mountain:string}>};
export function generateStaticParams(){return mountains.map(m=>({mountain:m.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const m=mountainBySlug((await params).mountain);if(!m)return {title:'가이드를 찾을 수 없습니다',robots:{index:false}};return {title:`${m.name} 가는 길과 코스 | 서울픽`,description:m.summary,alternates:{canonical:'/blog/seoul-mountains/'+m.slug},openGraph:{type:'article',title:`${m.name} 가는 길과 코스`,description:m.summary,images:[m.images[0].src],publishedTime:'2026-09-20',modifiedTime:m.verifiedAt}}}
export default async function MountainGuide({params}:Props){const m=mountainBySlug((await params).mountain);if(!m)notFound();const related=mountains.filter(x=>x.slug!==m.slug&&(x.difficulty===m.difficulty||x.tags.some(t=>m.tags.includes(t)))).slice(0,3);const url=siteOrigin+'/blog/seoul-mountains/'+m.slug;const schema=[{'@context':'https://schema.org','@type':'Article',headline:`${m.name} 가는 길과 코스`,description:m.summary,image:m.images.map(x=>new URL(x.src,siteOrigin).toString()),datePublished:'2026-09-20',dateModified:m.verifiedAt,inLanguage:'ko',mainEntityOfPage:url,author:{'@type':'Organization',name:'서울픽'}},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{ '@type':'ListItem',position:1,name:'홈',item:siteOrigin},{'@type':'ListItem',position:2,name:'블로그',item:siteOrigin+'/blog'},{'@type':'ListItem',position:3,name:'서울 산 BEST 10',item:siteOrigin+'/blog/seoul-mountains'},{'@type':'ListItem',position:4,name:m.name,item:url}]}];
 return <><Header/><main className="inner-main wrap mountain-detail"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><nav className="breadcrumbs" aria-label="현재 위치"><Link href="/">홈</Link><span>/</span><Link href="/blog">블로그</Link><span>/</span><Link href="/blog/seoul-mountains">서울 산 BEST 10</Link><span>/ {m.name}</span></nav>
 <header className="mountain-detail-head"><div><span className="accent-caption">서울픽 추천 10선 · {String(m.number).padStart(2,'0')}</span><h1>{m.name} 가는 길과<br/>대표 코스 가이드</h1><p>{m.summary}</p><div className="blog-dates">작성 2026-09-20 <span>·</span> 정보 확인 <time dateTime={m.verifiedAt}>{m.verifiedAt}</time></div><div className="action-row"><a href={m.mapUrl} target="_blank" rel="noopener noreferrer"><MapPin size={17}/>입구 지도 열기</a><MountainSave slug={m.slug}/></div></div><Image src={m.images[0].src} alt={m.images[0].alt} width={1200} height={900} sizes="(max-width: 900px) 100vw, 55vw" loading="eager"/></header>
 <div className="mountain-guide-layout"><aside className="blog-toc"><strong>목차</strong><ol><li><a href="#summary">30초 요약</a></li><li><a href="#access">가는 길</a></li><li><a href="#route">산에서 걷는 길</a></li><li><a href="#highlights">볼거리·사진 지점</a></li><li><a href="#prepare">준비와 방문 전 확인</a></li><li><a href="#after">하산 후 일정</a></li><li><a href="#faq">FAQ·출처</a></li></ol></aside><article className="blog-prose">
 <section id="summary"><h2>30초 요약</h2><div className="summary-box"><p><strong>{m.fit}</strong></p><p><TrainFront size={17}/> {m.line} {m.station} {m.exit} · {m.trailhead} 출발</p><p>{m.distance} · {m.duration} · {m.routeType} · 난이도 {m.difficulty}</p></div><div className="blog-table-scroll"><table><tbody><tr><th>시작·끝</th><td>{m.trailhead} → {m.end}</td></tr><tr><th>시간 기준</th><td>{m.timeBasis}</td></tr><tr><th>노면</th><td>{m.terrain.join(' · ')}</td></tr><tr><th>비용</th><td>{m.cost}</td></tr><tr><th>편의시설</th><td>{m.facilities.join(' · ')}</td></tr></tbody></table></div></section>
 <section id="access"><h2>지하철역에서 입구까지</h2>{m.access.map((p,i)=><p key={p}><strong>{i+1}.</strong> {p}</p>)}<p><AddressCopy address={`${m.station} ${m.exit} ${m.trailhead}`}/></p><figure><Image src={m.images[1].src} alt={m.images[1].alt} width={1200} height={800} sizes="(max-width: 700px) 100vw, 760px"/><figcaption>{m.images[1].caption} · 사진 출처와 라이선스는 하단 출처에서 확인할 수 있습니다.</figcaption></figure><div className="action-row"><a href={m.mapUrl} target="_blank" rel="noopener noreferrer"><MapPin size={17}/>실제 입구 지도</a><a href={m.routeMapUrl} target="_blank" rel="noopener noreferrer"><ExternalLink size={17}/>공식 코스 안내</a></div></section>
 <section id="route"><h2>산에서 걷는 길</h2><p>접근 구간이 끝나는 {m.trailhead}에서 산행을 시작합니다. 현장 이정표와 공식 지도를 우선하고, 갈림길에서는 다음 경유지 이름을 확인하세요.</p><ol className="mountain-route">{m.course.map((s,i)=><li key={s}><span>{i+1}</span><strong>{s}</strong></li>)}</ol><p>{m.timeBasis}. 같은 산에서도 출발점과 하산 방향이 달라지면 거리와 시간은 달라집니다.</p><figure><Image src={m.images[2].src} alt={m.images[2].alt} width={1200} height={800} sizes="(max-width: 700px) 100vw, 760px"/><figcaption>{m.images[2].caption}</figcaption></figure></section>
 <section id="highlights"><h2>볼거리와 사진 지점</h2>{m.highlights.map((x,i)=><p key={x}><strong>{x}</strong>{i===0?'에서는 대표 풍경을 넓게 담을 수 있습니다. 통행을 막지 않는 안전한 위치에서 촬영하세요.':i===1?'은 코스의 방향을 확인하면서 잠시 쉬기 좋은 지점입니다.':'은 계절과 날씨에 따라 시야가 크게 달라집니다.'}</p>)}<div className="mountain-gallery">{m.images.slice(3,5).map(x=><figure key={x.src}><Image src={x.src} alt={x.alt} width={700} height={520} sizes="(max-width: 700px) 100vw, 380px"/><figcaption>{x.caption}</figcaption></figure>)}</div></section>
 <section id="prepare"><h2>준비와 방문 전 확인</h2><ul>{m.preparation.map(x=><li key={x}>{x}</li>)}</ul><p>출발 직전에는 아래 항목을 공식 링크에서 다시 확인하세요. 실시간 연동이 없으므로 이 페이지는 당일 정상 운영이나 혼잡도를 표시하지 않습니다.</p><ul>{m.beforeVisit.map(x=><li key={x}>{x}</li>)}</ul><figure><Image src={m.images[5].src} alt={m.images[5].alt} width={1200} height={800} sizes="(max-width: 700px) 100vw, 760px"/><figcaption>{m.images[5].caption}</figcaption></figure></section>
 <section id="after"><h2>하산 후 이어갈 일정</h2><p>하산 방향과 가까운 일정부터 고르세요. 산 반대편의 장소를 바로 옆처럼 묶지 않았습니다.</p><ul>{m.afterHike.map(x=><li key={x}>{x}</li>)}</ul></section>
 <section id="faq" className="blog-faq"><h2>자주 묻는 질문</h2>{m.faq.map(x=><div key={x.question}><h3>{x.question}</h3><p>{x.answer}</p></div>)}</section><section className="blog-sources"><h2>공식 출처와 확인일</h2><p>교통·코스 정보 확인일: <time dateTime={m.verifiedAt}>{m.verifiedAt}</time></p><ul>{m.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.label}</a></li>)}<li><Link href="/photo-credits#mountains">사진 출처·라이선스 60건</Link></li></ul></section><Link href="/blog/seoul-mountains" className="button">10개 산 비교하기 <ArrowRight size={17}/></Link></article></div>
 <section className="related-blog"><div className="section-head"><h2>비슷한 산 가이드</h2><Link href="/blog/seoul-mountains" className="text-link">전체 비교 <ArrowRight size={16}/></Link></div><div className="mountain-grid">{related.map(x=><article className="mountain-card compact-mountain" key={x.slug}><Link href={'/blog/seoul-mountains/'+x.slug}><Image src={x.images[0].src} alt={x.images[0].alt} width={600} height={450} sizes="(max-width: 700px) 100vw, 160px"/></Link><div><span>{x.difficulty} · {x.routeType}</span><h2><Link href={'/blog/seoul-mountains/'+x.slug}>{x.name}</Link></h2><p>{x.summary}</p></div></article>)}</div></section></main><Footer/></>}
